#!/usr/bin/env bash
exec 2>&1
exec node_exporter \
		--path.rootfs=/rootfs/ \
		--path.sysfs=/sys \
		--path.procfs=/proc \
		--path.udev.data=/rootfs/run/udev/data \
		--collector.systemd \
		--collector.processes \
		--collector.textfile.directory=/etc/node-exporter \
		--collector.filesystem.mount-points-exclude=^/\(sys\|proc\|dev\|host\|etc\)\(\$\|/\) \
		--no-collector.ipvs
